services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80" # Expose only nginx to host on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
      # - stirling-pdf
  
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dms_root_password
      MYSQL_DATABASE: dms_db
      MYSQL_USER: dms_user
      MYSQL_PASSWORD: dms_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  laravel:
    container_name: laravel_app
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=dms_db
      - DB_USERNAME=dms_user
      - DB_PASSWORD=dms_password
    depends_on:
      - db
  
  

  stirling-pdf:
    container_name: stirling_pdf
    build:
      context: ./stirling
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB

networks:
  default:
    driver: bridge
